---
title: "Mathematics for Economic Analysis"
subtitle: "Logic and Proof"
author: Ozer Arabaci
date: ECON 6105, Uludag University
output:
  xaringan::moon_reader:
    css: ['default', 'metropolis', 'metropolis-fonts', 'ou-colors.css']
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

<style type="text/css">
  body{
  font-size: 12pt;
}
</style>


# Introduction

In this lecture we review the main logical rules in mathematics. 

## Topics to Cover

- The idea of a statement and  truth value 
- Deductive Reasoning vs. Inductive Reasoning
- Logical Connectives
- Converse, Inverse, and Contrapositive of a Statement
- Necessity and Sufficiency
- Mathematical Proof

---

# Statement and truth value 

- A **statement** is an assertion that is either **true** or **false** or **open**. 
- If a **statement** is ***true*** we say that its truth value is "True" (T). Similarly, a
false statement has truth value "False" (F). Otherwise, if we cannot decide whether it is ***true*** or ***false*** we can conclude that it has truth value ***Open*** (O).

> **QUESTION:**  What is the difference between a **statement** and a **proposition**?

## Examples

- Ankara is the capital city of Turkey
- $(x + y)^{2} = x^{2} + 2xy + y^{2}$
- NAFTA is a trade agreement signed by Canada, Mexico, and the United States. 
- All cats are white
-  All prime numbers are odd numbers.
- $x > y$
- $x^{2} - 9 = 0$

---

# Deductive vs. Inductive Reasoning

Logical reasoning can be classified as either deductive reasoning or inductive reasoning.

- **Deductive Reasoning:**  Reasoning based on consistent rules of logic. 

*Examples* : The cardinality of the real numbers be greater than that of the rational numbers. 

- **Inductive Reasoning:**  Reasoning based based on a set of observations. 

*Examples* : Auroras are formed when solar particles interact with the Earth’s magnetic field.


> **QUESTION:** Why inductive reasoning is not recognized as a form of proof in mathematics?

---

# Logical Connectives


- In logic, **logical connectives** (also called sentential connective, or sentential operator) are **operations** on statements which change their truth values or combine them to produce new statements.


## List of common logical connectives

- Negation (not): $\neg$
- Conjunction (and): $\land$
- Disjunction (or): $\lor$
- implication (if $\dots$ then): $\implies$
- Biconditional (if and only if): $\iff$

---

# Logical Connectives

Let $p$ be a statement. Then the statement " $p$ is **false**." is called the **negation** of $p$ and denoted by $\neg p$. The operation can be illustrated by a truth table:


| p     	|  $\neg p$ |
|-------	|-------	  |
| True  	| False 	  |
| False 	| True      |

## Example

- If  $p$ is “Today is Monday”, then $\neg p$ means “Today is not Monday”.
- if $p$ is $x \nless 2$ then $\neg p$ means $x \geq 2$


Let  $p$ be a statement. Then  $\neg(\neg p)$  is logically equivalent to $p$. More precisely $(\neg(\neg p)) \iff p$.

> **QUESTION:** Find $\neg p$ for $p :=(\forall x \in \mathbb{R}, \exists n \in \mathbb{Z}, x<n)$.


---

# Logical Connectives

Let $p$ and $q$ be statements. Then,  "*Both a and b are true.*"  is called a **conjunction** and denoted by $p \land q$. The operation can be illustrated by a truth table:


| $p$    | $q$     | $p \land q$ |
|-------|-------|---------   |
| True  | True  | True       |
| False | True  | False      |
| True  | False | False      |

## Example

- The Moon revolves around the Earth and elephant can fly.
- $x \leq 2 \land x \geq 1 \iff 1 \leq x \leq 2$

---

# Logical Connectives

“*Either a or b (or both) is true.*” is called a **disjunction** and denoted by $p \lor q$. 


| p     | q     | $p \lor q$ |
|-------|-------|---------|
| True  | True  | True    |
| False | True  | True    |
| True  | False | True    |
| False | False | False   |


## Example

- $0 \leq 1$ contains $0 < 1 \lor 0 = 1$

---

# Logical Connectives

“*If $p$ is true, then so is $q$.*” is called an **implication** and denoted by $p \implies q$.

- The order of $p$ and $q$ is not important in conjunction and disjunction. That is, $p \land q$ is the same as $q \land p$. 
- This is not true for an implication, which is written as “If **p then q”**, and denoted by $p \implies q$. 
- The statement $p$ is called the **hypothesis** and $q$ the **conclusion**. 
- Implication is also called a conditional statement.

## Example

- $x$ is the healthy person $\implies x$ is breathing.  
- $x > 0 \implies x^2 > 0$
- $xy = 0 \implies x = 0 \lor y = 0 \lor both$


> **QUESTION:** $x^2 > 0 \implies x > 0 ?$

---

# Logical Connectives
