---
title: "Mathematics for Economic Analysis"
subtitle: "Real Analysis Cont."
author: Ozer Arabaci
date: ECON 6105, Uludag University
output:
  xaringan::moon_reader:
    css: ['default', 'metropolis', 'metropolis-fonts', 'ou-colors.css']
    self_contained: false
    seal: true
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r xaringanExtra, echo=FALSE}
xaringanExtra::use_xaringan_extra(c("tile_view","tachyons"))
xaringanExtra::use_logo("uu_logo.png", position = xaringanExtra::css_position(top = "10px"),width = "65px")
```

<style>
.remark-slide-content.hljs-default {
  border-top: 40px solid #23373B;
}

.remark-slide-content > h1 {
  font-size: 40px;
  margin-top: -80px;
}

</style>



# Introduction

In this lecture we review the basic topic in real analysis. 

## Topics to Cover

- Binary Operations
- Group
- Fields
- Vector Space
- Inner Product Space
- Normed Vector Space
- Metric Space

---

# Binary Operation

.bg-washed-red.br1.shadow-3.ph2.mt3[
**`r icon::fa("info-circle")` Definition**

*Let $G$ be a set. A binary operation on $G$ is a function that assigns each ordered pair of elements of $G$ an element of $G$. *
]

.bg-washed-green.br1.shadow-3.ph2.mt3[
**`r icon::fa("lightbulb")` Example**

Let $a, b \in \mathbb{R}$ Then, apply $\oplus$ (usual addition) on $a$ and $b$. If  $a \oplus b \in \mathbb{R}$ that means the $\oplus$ operator is a *binary operator*.
]

.bg-washed-blue.br1.shadow-3.ph2.mt3[
**`r icon::fa("comment-dots")` Notes**

- In the set of $\mathbb{N}, \mathbb{Z}, \mathbb{R}$, and $\mathbb{C}$  + and $\times$ are binary operations. 
- In the set of $\mathbb{N}$, - and \ are not binary operations.
]


---

# Group

.bg-washed-red.br1.shadow-3.ph2.mt3[
**`r icon::fa("info-circle")` Definition**

*Let $G$ a set together with a binary operation that assigns each ordered pair $(a,b)$ of elements of $G$ an element in $G$, donated by $ab$. We say $G$ is a group under this operation if the following three properties are satisfied.* 

- **Associativity **: $(ab)c = a(bc), \forall a,b,c \in G$
- **Identity**: $\exists e \forall a \in G \ni ae = ea = a$
- **Inverse**: $\exists b \forall a \in G \ni ab = ba = e$
]

.bg-washed-blue.br1.shadow-3.ph2.mt3[
**`r icon::fa("comment-dots")` Note**

A group is said to be an **Abelian** group if it satisfy $ab = ba, \forall a,b \in G$
]

---

# Group

.bg-washed-green.br1.shadow-3.ph2.mt3[
**`r icon::fa("lightbulb")` Example**

Let set to be $\mathbb{R}$ and opetation $\oplus$. If $\forall a,b \in \mathbb{R}$ then

- $a \oplus b \in \mathbb{R} \implies \oplus$ is binary operator. 
- **Associativity **: $(a \oplus b) \oplus c = a \oplus(b \oplus c), \forall a,b,c  \in \mathbb{R}$
- **Identity**: $\exists e \forall a \in \mathbb{R} \ni a \oplus e = e \oplus a = a \implies e = 0 \in \mathbb{R}$
- **Inverse**:  $\exists b \forall a \in \mathbb{R} \ni a \oplus b = b \oplus a = e = 0 \implies b = -a \in \mathbb{R}$
]


.bg-washed-blue.br1.shadow-3.ph2.mt3[
**`r icon::fa("comment-dots")` Notes**

- The set of $\mathbb{Z},$ the set of  $\mathbb{Q}$ and the set of  $\mathbb{R}$ are all groups under ordinary addition. In each case, the identity is $0$ and the inverse of an element $a$ is $-a$. In fact, all these are *Abelian* groups.
- The set $S=\left\{A \in \mathbb{R}^{2 \times 2}:|A| \neq 0\right\}$ under usual multiplication forms a *non-Abelian* group.
- The set of integers $\mathbb{Z} /\{0\}$ under ordinary multiplication is not a group. Since the inverse of any $x \in \mathbb{Z}(x \neq 1,-1),$ is $\frac{1}{x} \notin \mathbb{Z}$
]

---

# Fields

.bg-washed-red.br1.shadow-3.ph2.mt3[
**`r icon::fa("info-circle")` Definition**

A non empty set $\mathbb{F}$ equipped with two binary operations addition $\oplus: \mathbb{F} \times \mathbb{F} \rightarrow \mathbb{F}$  where $(a, b) \mapsto a \oplus b$ and multiplication $\otimes: \mathbb{F} \times \mathbb{F} \rightarrow \mathbb{F}$ where $(a, b) \mapsto a \otimes b$ is said to be a field if it satisfies the following axioms $\forall a, b, c \in \mathbb{F}:$

- **Commutativity of addition and multiplication:**
  - $a\oplus b = b \oplus a$ and $a \otimes b = b \otimes a$
- **Associativity of addition and multiplication:**
  - $(a\oplus b)\oplus c = a\oplus(b\oplus c)$ and $(a \otimes b) \otimes c= a \otimes (b \otimes c)$
- **Existence of additive and multiplicative identities:**
  - $0 \oplus a = a$ and $1 \otimes a = a$
- **Existence of additive and multiplicative inverses:**
  - $a\oplus (-a) = 0$ and $b \otimes \frac{1}{b}=1$ (where $b \neq 0 \in \mathbb{F}$)
]
 
.bg-washed-green.br1.shadow-3.ph2.mt3[
**`r icon::fa("lightbulb")` Example**
- The set of $\mathbb{R}$ and $\mathbb{Z}$ with the $\oplus$ and $\otimes$ is a field.
- The Euclidean set $\mathbb{R}^{2}$ with the $\oplus$ and $\otimes$ is not a field.
]


---

# Vector Space


.bg-washed-red.br1.shadow-3.ph2.mt3[
**`r icon::fa("info-circle")` Definition**

Vector space $(V, \mathbb{F})$ is a set of vectors, and a field of scalars $\mathbb{F}$ equipped with (binary) Operations:
- **Vector Addition:** $\oplus: V \times V \rightarrow V$  where $(a, b) \mapsto a \oplus b$
- **Scalar Multiplication:** $\oplus: \mathbb{F} \times V \rightarrow V$ where $(\gamma, a) \mapsto \gamma \otimes a$ 

that satisfies the following axioms or all $a, b, c \in V$ and $\gamma, \lambda \in \mathbb{F}:$


- **Commutativity of addition**: $x \oplus y = y \oplus x$
- **Additive identity**: $a \oplus \mu =a$ where $\mu = \begin{pmatrix} 0 & 0 & 0 & 0 \dots \end{pmatrix}$ 
- **Negative Vector**: $\forall a \in V, \exists\theta \ni a \oplus \theta = 0$ where $\theta = -a \in V$
- **Associativity of multiplication**: $\gamma \otimes (\lambda \otimes a) = (\gamma \otimes \lambda) \otimes a$
- **Multiplicative identity**:  $a \otimes \delta = a$ where $\delta = \begin{pmatrix} 1 & 1 & 1 & 1 \dots \end{pmatrix}$ 
- **Negative Vector**: $\forall a \in V, \exists\theta \ni a \otimes \theta = 0$ where $\theta = -a \in V$
- **First distributive law**:  $(\gamma + \lambda) \otimes a = \gamma \otimes a \oplus \lambda \otimes a$ 
- **Second distributive law**: $\gamma \otimes (a \oplus b)= \gamma \otimes a \oplus \gamma \otimes b$
]


---

# Vector Space

## Examples


.pull-left[
.bg-washed-green.br1.shadow-3.ph2.mt3[
**Vector Space**

- $\mathbb{R}^{n}$ is a vector space over the field $\mathbb{R}$
- $\mathbb{R}^{m \times n}-$ Space of matrices is a vector space over $\mathbb{R}$
- The set of functions: continuous functions that map an interval of the real line to $\mathbb{R}^{n} ;\left(F\left(\left[t_{1}, t_{2}\right], \mathbb{R}^{n}\right), \mathbb{R}\right)$

]]

.pull-right[
.bg-washed-green.br1.shadow-3.ph2.mt3[
**Not Vector Space**

- $S=\left\{\left[\begin{array}{l}a \\ b\end{array}\right] \in \mathbb{R}^{2} \mid a \geq 0\right\}$
- $S=\left\{\left[\begin{array}{l}a \\ b\end{array}\right] \in \mathbb{R}^{2} \mid b = 1\right\}$
- $S=\left\{\left[\begin{array}{l}a \\ b\end{array}\right] \in \mathbb{R}^{2} \mid b=2 a+1\right\}$

]]


---
# Inner Product Space

.bg-washed-red.br1.shadow-3.ph2.mt3[
**`r icon::fa("info-circle")` Definition**

The **inner product** or **dot product** of $\mathbb{R}^{n}$ is a function $\langle,\rangle$ defined by

$\langle\boldsymbol{u}, \boldsymbol{v}\rangle=a_{1} b_{1}+a_{2} b_{2}+\cdots+a_{n} b_{n} \quad \text { for } \boldsymbol{u}=\left[a_{1}, a_{2}, \ldots, a_{n}\right]^{T}, \boldsymbol{v}=\left[b_{1}, b_{2}, \ldots, b_{n}\right]^{T} \in \mathbb{R}^{n}$

The inner product $\langle,\rangle$ satisfies the following properties:

- **Linearity:** $\langle a \boldsymbol{u}+b \boldsymbol{v}, \boldsymbol{w}\rangle=a\langle\boldsymbol{u}, \boldsymbol{w}\rangle+b\langle\boldsymbol{v}, \boldsymbol{w}\rangle$
- **Symmetry:** $\langle u, v\rangle=\langle v, u\rangle$
- **Positive Definite**: $u \in V,\langle u, u\rangle \geq 0 ;$ and $\langle u, u\rangle=0 \iff u=0$


]

.bg-washed-green.br1.shadow-3.ph2.mt3[
**`r icon::fa("lightbulb")` Example**

Let $\mathbf{v}=\left[\begin{array}{c}1 & -1 &  4\end{array}\right]$, $\mathbf{w} = [2 \quad 2  \quad 0].$ Then $\mathbf{v} \cdot \mathbf{w}=1 \cdot 2+(-1) \cdot 2+4 \cdot 0=0$
]

.bg-washed-blue.br1.shadow-3.ph2.mt3[
**`r icon::fa("comment-dots")` Note**

With the dot product we have geometric concepts such as the **length of a vector**, **the angle between two vectors**, **orthogonality**, etc. We will use these concepts to describe the geometric concepts of vector spaces.
]

---
# Inner Product Space


.bg-washed-red.br1.shadow-3.ph2.mt3[
**`r icon::fa("info-circle")` Definition**

An **inner product** of a real vector space $V$ is an assignment that for any two vectors $u, v \in V,$ there is a real number $\langle\boldsymbol{u}, \boldsymbol{v}\rangle,$ satisfying the following properties:

- **Linearity:** $\langle a \boldsymbol{u}+b \boldsymbol{v}, \boldsymbol{w}\rangle=a\langle\boldsymbol{u}, \boldsymbol{w}\rangle+b\langle\boldsymbol{v}, \boldsymbol{w}\rangle$
- **Symmetry:** $\langle u, v\rangle=\langle v, u\rangle$
- **Positive Definite**: $u \in V,\langle u, u\rangle \geq 0 ;$ and $\langle u, u\rangle=0 \iff u=0$

The **vector space** $V$ with an **inner product** is called a **(real) inner product space**.

]

.bg-washed-green.br1.shadow-3.ph2.mt3[
**`r icon::fa("lightbulb")` Example**

The vector space $\mathbb{R}^{n}$ with the dot product $\boldsymbol{u} \cdot \boldsymbol{v}=a_{1} b_{1}+a_{2} b_{2}+\cdots+a_{n} b_{n}$ where $\boldsymbol{u}=\left[a_{1}, a_{2}, \ldots, a_{n}\right]^{T}, \boldsymbol{v}=\left[b_{1}, b_{2}, \ldots, b_{n}\right]^{T} \in \mathbb{R}^{n},$ is an **inner product space**. The vector space $\mathbb{R}^{n}$ with this special inner product (dot product) is called the **Euclidean $n$-space**, and the dot product is called the standard inner product on $\mathbb{R}^{n}$. 
]



---
# Normed Vector Space

.bg-washed-red.br1.shadow-3.ph2.mt3[
**`r icon::fa("info-circle")` Definition**

Given any vector space $V$, a norm on $V$ is a function $\|\cdot\|: V \rightarrow \mathbb{R}$ such that for all $a, b \in V$ and $\alpha \in \mathbb{R}:$

- **Positive:** $\|a\| \geq 0$ and $\|a\| = 0 \iff a = 0$
- **Homogeneous:** $\|\alpha a\| = \|\alpha\| \|a\|$
- **Triangle inequality**: $\|a+b\| \leq\|a\|+\|b\|$ 

The **vector space** $V$ with an **inner product** is called a **(real) inner product space**.

]

.bg-washed-blue.br1.shadow-3.ph2.mt3[
**`r icon::fa("comment-dots")` Note**

The homogeneous condition ensures that the norm of the zero vector in $V$ is $0$; this condition is often included in the definition of a norm.
]

.bg-washed-green.br1.shadow-3.ph2.mt3[
**`r icon::fa("lightbulb")` Example**

Common examples of norms on $\mathbb{R}^{n}$ are the $\ell_{p}$ norms, where $1 \leq p \leq \infty$, defined by
$\ell_{p}(x)=\left\{\sum_{j=1}^{n}\left|x_{j}\right|^{p}\right\}^{1 / p}$
]


---
# Normed Vector Space

.bg-washed-red.br1.shadow-3.ph2.mt3[
**`r icon::fa("info-circle")` Definition**

A normed vector space is a pair $(V,\|\cdot\|)$ where $V$ is a vector space and $\|\cdot\|: V \rightarrow \mathbb{R}$ is a **norm**.
]

.bg-washed-blue.br1.shadow-3.ph2.mt3[
**`r icon::fa("comment-dots")` Note**
It is standard to view any normed vector space $(V,\|\cdot\|)$ as a **metric space** where the metric $d(a, b)=\|x-y\| \quad \forall a, b \in V$.

]

.bg-washed-green.br1.shadow-3.ph2.mt3[
**`r icon::fa("lightbulb")` Example**

- $V=\mathbb{R}^{K},$ with $\|x\|=\left[\sum_{k=1}^{K} x_{k}^{2}\right]^{\frac{1}{2}}$ (Euclidean Space)
- $V = \mathbb{R}^{K},$ with $\|x\|=\max _{i}\left|x_{i}\right|$
- $V = \mathbb{R}^{K},$ with $\|x\|=\sum_{k=1}^{K}\left|x_{k}\right|$
]



---
# Metric Space

.bg-washed-red.br1.shadow-3.ph2.mt3[
**`r icon::fa("info-circle")` Definition**

Given any set $X$, the function $d: X \times X \rightarrow \mathbb{R}$ is a metric or distance function on $X$ if the following properties hold:

- **Positivity:** $d(x, y) \geq 0$ for all $x, y \in X,$ with $d(x, y)=0 \iff x=y$
- **Symmetry:** $d(x, y)=d(y, x)$
- **Triangle Inequality:** $d(x, z) \leq d(x, y)+d(y, z), \forall x, y, z \in X$

A function d satisfying conditions (i)-(iii), is called a metric on $X$.
]

.bg-washed-green.br1.shadow-3.ph2.mt3[
**`r icon::fa("lightbulb")` Example**

- $d(x, y)=\left(\sum_{i \in K}\left(x_{i}-y_{i}\right)^{2}\right)^{1 / 2}$
- Let $p \in \mathbb{R}_{+}$ and $d_{p}: \mathbb{R}^{K} \times \mathbb{R}^{K} \rightarrow \mathbb{R}$ by $d_{p}(x, y)=\left(\sum_{i \in K}\left|x_{i}-y_{i}\right|^{p}\right)^{\frac{1}{\rho}}$
- The $d_{p}$ is a distance if only if $p \geq 1$
]










